function [Psi_p,Psi_d] = jfactor(Pi_ss,nz,nw)
%JFACTOR Primal and dual J-spectral factors of a strict PN multiplier.
% Frequency-domain checks below are numerical checks on a finite grid.

tol = 1e-9;
checkTol = 1e-6;
wcheck = [0,logspace(-4,4,200)];
n = nz + nw;

Pi_ss = minreal(ss(Pi_ss),tol);  % The original code used undefined Pi.

%% Basic guards
if size(Pi_ss,1) ~= n || size(Pi_ss,2) ~= n
    error('Pi must be (%d x %d).',n,n);
end
if Pi_ss.Ts ~= 0 || ~isproper(Pi_ss) || ~isreal(Pi_ss)
    error('Pi must be real-rational, continuous-time, and proper.');
end
if any(abs(real(pole(Pi_ss))) < tol)
    error('Pi has a pole on or too close to the imaginary axis.');
end

Jp = blkdiag(eye(nz),-eye(nw));
Jd = blkdiag(eye(nw),-eye(nz));
Jhat = [zeros(nz,nw), eye(nz); ...
       -eye(nw),      zeros(nw,nz)];

check_PN(Pi_ss,nz,nw,wcheck,tol,checkTol,'primal multiplier');

%% Stable/anti-stable separation
[Pi_stab,~] = stabsep(Pi_ss);
Pi_stab = minreal(Pi_stab,tol);
[A,B,C,D] = ssdata(Pi_stab);

%% D = W.'*Jp*W
[W,J,errD] = congruence_factor_D(D,tol);
if ~isequal(size(J),size(Jp)) || norm(J-Jp,'fro') > tol
    error('The inertia of D does not match (nz,nw) = (%d,%d).',nz,nw);
end
if errD > checkTol
    error('D congruence residual is too large: %.3e.',errD);
end

%% Stabilizing ARE
nx = size(A,1);
if nx == 0
    Psi_p = ss(W);
else
    Q = zeros(nx);
    [X,~,~,info] = icare(A,B,Q,D,C.');
    if isempty(X) || info.Report ~= 0
        error('icare failed; report code %d.',info.Report);
    end

    K = D\(B.'*X+C);
    areResidual = A.'*X + X*A - (X*B+C.')*K;
    if norm(areResidual,'fro') > checkTol*max(1,norm(X,'fro'))
        error('ARE residual is too large.');
    end
    if max(real(eig(A-B*K))) >= -tol
        error('The ARE solution is not stabilizing.');
    end

    Cpsi = Jp*(W.'\(B.'*X+C));
    Psi_p = minreal(ss(A,B,Cpsi,W),tol);
end

check_factor(Psi_p,'primal factor',tol);
check_factorization(Pi_ss,Psi_p,Jp,wcheck,checkTol);

%% Dual factor: (Jhat' * transpose(Psi_p) * Jhat)^(-1)
[Ap,Bp,Cp,Dp] = ssdata(Psi_p);
Dh = Jhat'*Dp.'*Jhat;
if rcond(Dh) < tol
    error('The feedthrough of the dualized factor is singular.');
end

Dd = Dh\eye(n);
Ad = Ap.' - Cp.'*Jhat*Dd*Jhat'*Bp.';
Bd = Cp.'*Jhat*Dd;
Cd = -Dd*Jhat'*Bp.';
Psi_d = minreal(ss(Ad,Bd,Cd,Dd),tol);

check_factor(Psi_d,'dual factor',tol);
check_dual_identity(Psi_p,Psi_d,Jhat,wcheck,checkTol);

% The multiplier generated by the dual factor should also be strict PN.
Pi_d = @(w) evalfr(Psi_d,1i*w)'*Jd*evalfr(Psi_d,1i*w);
check_PN_handle(Pi_d,Psi_d.D'*Jd*Psi_d.D,nw,nz,wcheck,tol,'dual multiplier');

fprintf('jfactor: all numerical checks passed.\n');
end

function [W,J,err] = congruence_factor_D(D,tol)
% Find W,J such that D = W.'*J*W.
if norm(D-D.','fro') > tol*max(1,norm(D,'fro'))
    error('The feedthrough D is not symmetric.');
end
D = (D+D.')/2;
[V,L] = eig(D);
lam = real(diag(L));
scale = max(1,norm(D,2));
if any(abs(lam) <= tol*scale)
    error('The feedthrough D is singular.');
end

pos = find(lam > 0);
neg = find(lam < 0);
idx = [pos;neg];
lam = lam(idx);
V = V(:,idx);
J = blkdiag(eye(numel(pos)),-eye(numel(neg)));
W = diag(sqrt(abs(lam)))*V.';
err = norm(D-W.'*J*W,'fro')/max(1,norm(D,'fro'));
end

function check_factor(G,name,tol)
% A proper square factor is stably invertible iff both A and A-B/D*C
% are Hurwitz and D is nonsingular.
[A,B,C,D] = ssdata(G);
if ~isempty(A) && max(real(eig(A))) >= -tol
    error('The %s is not stable.',name);
end
if rcond(D) < tol
    error('The %s has singular feedthrough.',name);
end
Ainv = A-B*(D\C);
if ~isempty(Ainv) && max(real(eig(Ainv))) >= -tol
    error('The inverse of the %s is not stable.',name);
end
end

function check_factorization(Pi,Psi,J,wcheck,checkTol)
err = factor_error(Pi.D,Psi.D,J);
for w = wcheck
    err = max(err,factor_error(evalfr(Pi,1i*w),evalfr(Psi,1i*w),J));
end
if err > checkTol
    error('Primal factorization residual is too large: %.3e.',err);
end
end

function err = factor_error(PiValue,PsiValue,J)
err = norm(PiValue-PsiValue'*J*PsiValue,'fro')/max(1,norm(PiValue,'fro'));
end

function check_dual_identity(Psi_p,Psi_d,Jhat,wcheck,checkTol)
n = size(Jhat,1);
err = dual_error(Psi_p.D,Psi_d.D,Jhat,n);
for w = wcheck
    Hp = evalfr(Psi_p,1i*w);
    Hd = evalfr(Psi_d,1i*w);
    err = max(err,dual_error(Hp,Hd,Jhat,n));
end
if err > checkTol
    error('Dual-factor identity residual is too large: %.3e.',err);
end
end

function err = dual_error(Hp,Hd,Jhat,n)
err = norm(Hd*(Jhat'*Hp.'*Jhat)-eye(n),'fro');
end

function check_PN(Pi,nz,nw,wcheck,pnTol,checkTol,name)
Pinf = Pi.D;
if norm(Pinf-Pinf','fro') > checkTol*max(1,norm(Pinf,'fro'))
    error('The %s is not Hermitian at infinity.',name);
end
check_PN_handle(@(w) evalfr(Pi,1i*w),Pinf,nz,nw,wcheck,pnTol,name,checkTol);
end

function check_PN_handle(PiValue,Pinf,nz,nw,wcheck,pnTol,name,checkTol)
if nargin < 8
    checkTol = 1e-6;
end
values = cell(1,numel(wcheck)+1);
values{1} = Pinf;
for k = 1:numel(wcheck)
    values{k+1} = PiValue(wcheck(k));
end
for k = 1:numel(values)
    P = values{k};
    if norm(P-P','fro') > checkTol*max(1,norm(P,'fro'))
        error('The %s is not Hermitian on the check grid.',name);
    end
    P11 = (P(1:nz,1:nz)+P(1:nz,1:nz)')/2;
    P22 = (P(nz+1:nz+nw,nz+1:nz+nw)+P(nz+1:nz+nw,nz+1:nz+nw)')/2;
    if (~isempty(P11) && min(real(eig(P11))) <= pnTol) || ...
       (~isempty(P22) && max(real(eig(P22))) >= -pnTol)
        error('The %s is not strictly PN on the check grid.',name);
    end
end
end
