%% iqc_repeated_real_lti_pNv2_multi_system.m
% IQC/LMI script for testing multiple LFR systems with a repeated real LTI
% parametric uncertainty, using the p = N*v2 augmentation.
%
% Uncertain interconnection:
%   q = G_qp p + G_qw w
%   z = G_zp p + G_zw w
%   p = delta * I_r * q,     delta in R, |delta| <= alpha.
%
% Dynamic multiplier basis:
%   v1 = alpha*(psi_nu kron I_r)*q
%   v2 =        (psi_nu kron I_r)*p
%
% Since the first basis element is psi_0(s)=1, the first r components of v2
% are exactly p. Hence
%   p = N*v2,   N = [I_r 0 ... 0].
%
% This file treats v2 as the IQC input and builds the augmented map
%   [v2; w]  ->  [v1; z]
% with p substituted by N*v2. This avoids adding a dynamic multiplier output
% driven by p in the main plant realization. The resulting test is sufficient
% for analysis because it enforces the dissipation inequality for all v2,
% including the subset v2=(psi kron I_r)*p generated by true trajectories.
%
% Dependencies:
%   - MATLAB Control System Toolbox
%   - YALMIP
%   - SDP solver supported by YALMIP, e.g. MOSEK, SeDuMi, SDPT3
%
% How to use:
%   1. Add/replace entries in the "Plants to test" section.
%   2. Each plant must be an LFR realization with matrices
%      A, Bp, Bw, Cq, Dqp, Dqw, Cz, Dzp, Dzw.
%   3. This file assumes np = nq = r and Delta = delta*I_r.

clear; clc; close all;
yalmip('clear');

%% Solver and analysis settings
solverName = '';        % examples: 'mosek', 'sedumi', 'sdpt3'; empty lets YALMIP choose
lmiTol     = 1e-8;      % strictness surrogate; try 1e-9 or 0 if numerically fragile

nuList     = 0:3;
rho        = -1;
basisType  = '12a';
alphaGrid  = linspace(0,1,51);

%% Plants to test
plants = {};

% 1) Paper Example 8.1. This is the full LFR from Eq. (94).
plants{end+1} = make_example81_lfr();

% 2) Template for your own system. Uncomment and replace the matrices.
%    Dimensions must satisfy:
%       A    nx x nx
%       Bp   nx x r       Bw   nx x nw
%       Cq   r  x nx      Dqp  r  x r       Dqw  r  x nw
%       Cz   nz x nx      Dzp  nz x r       Dzw  nz x nw
%    Then Delta = delta*I_r closes p = Delta*q.
%
% A   = [-1  0; 0 -2];
% Bp  = [1; 0];
% Bw  = [0; 1];
% Cq  = [1 0];
% Dqp = 0;
% Dqw = 0;
% Cz  = [0 1];
% Dzp = 0;
% Dzw = 0;
% plants{end+1} = make_lfr('my custom 1x1 uncertainty plant', ...
%     A,Bp,Bw,Cq,Dqp,Dqw,Cz,Dzp,Dzw);

%% Run all plants
allResults = cell(numel(plants),1);

for kPlant = 1:numel(plants)
    plant = plants{kPlant};
    validate_repeated_scalar_lfr(plant);

    fprintf('\n=== Plant %d/%d: %s ===\n',kPlant,numel(plants),plant.name);
    fprintf('nx=%d, r=np=nq=%d, nw=%d, nz=%d\n', ...
        size(plant.A,1), size(plant.Bp,2), size(plant.Bw,2), size(plant.Cz,1));

    gammaBound = nan(numel(alphaGrid),numel(nuList));
    statusText = strings(numel(alphaGrid),numel(nuList));

    for j = 1:numel(nuList)
        nu = nuList(j);
        fprintf('  nu = %d\n',nu);
        for i = 1:numel(alphaGrid)
            alpha = alphaGrid(i);
            out = iqc_repeated_real_lti_bound_pNv2(plant,alpha,nu,rho,basisType,solverName,lmiTol);
            gammaBound(i,j) = out.gamma;
            statusText(i,j) = out.status;
            fprintf('    alpha = %.3f: gamma = %.6g (%s)\n',alpha,out.gamma,out.status);
        end
    end

    result = struct();
    result.plant = plant;
    result.alphaGrid = alphaGrid;
    result.nuList = nuList;
    result.rho = rho;
    result.basisType = basisType;
    result.gammaBound = gammaBound;
    result.statusText = statusText;
    allResults{kPlant} = result;

    figure('Name',['IQC p=Nv2 bounds - ' plant.name]);
    plot(alphaGrid,gammaBound,'LineWidth',1.5);
    ylim([0,100])
    grid on;
    xlabel('\alpha');
    ylabel('\gamma');
    legend(compose('\\nu = %d',nuList),'Location','NorthWest');
    title(['p=Nv_2 IQC upper bounds for ' plant.name],'Interpreter','none');
end

%% Optional save
% save('iqc_pNv2_multi_system_results.mat','allResults');

%% Local functions
function plant = make_example81_lfr()
% LFR from Eq. (94) of Example 8.1.
% State x has dimension 2, uncertainty channel has r=2,
% disturbance channel has nw=1, performance output has nz=1.

    A   = [-2 -3;
            1  1];

    Bp  = [1 0;
           0 0];
    Bw  = [1;
           0];

    Cq  = [1 0;
           0 0];
    Dqp = [1 -2;
           1 -1];
    Dqw = [0;
           1];

    Cz  = [1 0];
    Dzp = [0 1];
    Dzw = 0;

    plant = make_lfr('Example 8.1 Eq. (94)',A,Bp,Bw,Cq,Dqp,Dqw,Cz,Dzp,Dzw);
end

function plant = make_lfr(name,A,Bp,Bw,Cq,Dqp,Dqw,Cz,Dzp,Dzw)
% Pack an LFR realization.
    plant = struct();
    plant.name = name;
    plant.A = A;
    plant.Bp = Bp;
    plant.Bw = Bw;
    plant.Cq = Cq;
    plant.Dqp = Dqp;
    plant.Dqw = Dqw;
    plant.Cz = Cz;
    plant.Dzp = Dzp;
    plant.Dzw = Dzw;
end

function validate_repeated_scalar_lfr(plant)
% Checks dimensional assumptions used by this script.
% Stability and well-posedness are required theoretically; this function warns
% about obvious problems but does not prove robust well-posedness.

    A = plant.A; Bp = plant.Bp; Bw = plant.Bw;
    Cq = plant.Cq; Dqp = plant.Dqp; Dqw = plant.Dqw;
    Cz = plant.Cz; Dzp = plant.Dzp; Dzw = plant.Dzw;

    nx = size(A,1);
    assert(size(A,2)==nx, 'A must be square.');
    assert(size(Bp,1)==nx && size(Bw,1)==nx, 'Bp and Bw must have nx rows.');
    assert(size(Cq,2)==nx && size(Cz,2)==nx, 'Cq and Cz must have nx columns.');

    r  = size(Bp,2);
    nw = size(Bw,2);
    nq = size(Cq,1);
    nz = size(Cz,1);

    assert(nq==r, 'This solver assumes Delta = delta*I_r, so size(Cq,1) must equal size(Bp,2).');
    assert(all(size(Dqp)==[r r]), 'Dqp must be r x r.');
    assert(all(size(Dqw)==[r nw]), 'Dqw must be r x nw.');
    assert(all(size(Dzp)==[nz r]), 'Dzp must be nz x r.');
    assert(all(size(Dzw)==[nz nw]), 'Dzw must be nz x nw.');

    if any(real(eig(A)) >= -1e-10)
        warning('Nominal A is not strictly Hurwitz. The IQC theorem used here assumes stable nominal G.');
    end
end

function out = iqc_repeated_real_lti_bound_pNv2(plant,alpha,nu,rho,basisType,solverName,lmiTol)
% Solves the p=N*v2 augmented IQC LMI at one alpha, nu, and rho for
% Delta = delta*I_r, delta real, |delta| <= alpha.
%
% Class 5 dynamic DG multiplier:
%   v1 = alpha*(psi kron I_r)*q,
%   v2 =        (psi kron I_r)*p,
%   P  = [P11 P12; P12' -P11].
%
% Main augmentation:
%   p = N*v2,   N = [I_r 0 ... 0],
%   [v2;w] -> [v1;z].
%
% The code imposes P12 + P12' = 0, a simple sufficient condition for the
% equality constraint in Class 5.

    if nargin < 7 || isempty(lmiTol)
        lmiTol = 1e-8;
    end

    A   = plant.A;   Bp  = plant.Bp;  Bw  = plant.Bw;
    Cq  = plant.Cq;  Dqp = plant.Dqp; Dqw = plant.Dqw;
    Cz  = plant.Cz;  Dzp = plant.Dzp; Dzw = plant.Dzw;

    nxG = size(A,1);
    rDelta = size(Bp,2);       % np = nq = rDelta
    nw = size(Bw,2);
    nz = size(Cz,1);

    [Apsi,Bpsi,Cpsi,Dpsi] = basis_realization(nu,rho,basisType);
    [ApsiK,BpsiK,CpsiK,DpsiK] = kron_i_realization(Apsi,Bpsi,Cpsi,Dpsi,rDelta);

    nPsiState = size(ApsiK,1);
    m = rDelta*(nu+1);         % dimension of v1 and v2
    N = [eye(rDelta), zeros(rDelta,m-rDelta)];

    % Optional sanity check for the selection property p=N*v2. For the basis
    % functions used here, the first output block of (psi kron I_r)*p is p.
    if norm(N*DpsiK - eye(rDelta), 'fro') > 1e-8
        warning('N*DpsiK is not identity. Check basis output ordering.');
    end
    if nPsiState > 0 && norm(N*CpsiK, 'fro') > 1e-8
        warning('N*CpsiK is not zero. Check basis realization/output ordering.');
    end

    % Augmented map from input [v2;w] to output [v1;z].
    % States are original plant state x and the q-filter state x_psi,q.
    % The p-filter is not included as an output generator; v2 is an input and
    % p is selected algebraically as p=N*v2.
    nx = nxG + nPsiState;

    Ahat = [ A,                         zeros(nxG,nPsiState);
             BpsiK*Cq,                  ApsiK ];

    Bhat = [ Bp*N,                      Bw;
             BpsiK*Dqp*N,               BpsiK*Dqw ];

    Cv1 = alpha*[DpsiK*Cq,              CpsiK];
    Dv1 = alpha*[DpsiK*Dqp*N,           DpsiK*Dqw];

    Czbar = [Cz,                        zeros(nz,nPsiState)];
    Dzbar = [Dzp*N,                     Dzw];

    % Static output used in the KYP inequality:
    %   y = [v1; v2; w].
    Cstatic = [ Cv1;
                zeros(m,nx);
                zeros(nw,nx) ];

    Dstatic = [ Dv1;
                eye(m),                 zeros(m,nw);
                zeros(nw,m),            eye(nw) ];

    nY = 2*m + nw;

    % Decision variables.
    X     = sdpvar(nx,nx,'symmetric');
    P11   = sdpvar(m,m,'symmetric');
    P12   = sdpvar(m,m,'full');
    gamma = sdpvar(1,1);

    Piqc = [P11,  P12;
            P12', -P11];

    Qstatic = [ Piqc,                 zeros(2*m,nw);
                zeros(nw,2*m),       -gamma*eye(nw) ];

    Constraints = [];
    Constraints = [Constraints, gamma >= 1e-7, gamma <= 1e4];
    Constraints = [Constraints, P12 + P12' == 0];

    % KYP LMI for (psi kron I_r)' P11 (psi kron I_r) >= 0.
    if nPsiState == 0
        Constraints = [Constraints, P11 >= lmiTol*eye(m)];
    else
        Xnu = sdpvar(nPsiState,nPsiState,'symmetric');

        Lpsi = [ eye(nPsiState),      zeros(nPsiState,rDelta);
                 ApsiK,              BpsiK;
                 CpsiK,              DpsiK ];

        Mpsi = [ zeros(nPsiState),    Xnu,                         zeros(nPsiState,m);
                 Xnu,                 zeros(nPsiState),             zeros(nPsiState,m);
                 zeros(m,nPsiState),  zeros(m,nPsiState),           P11 ];

        PosLMI = Lpsi'*Mpsi*Lpsi;
        Constraints = [Constraints, PosLMI >= lmiTol*eye(size(PosLMI,1))];
    end

    % Main robust-performance KYP LMI. Columns are [xhat; v2; w].
    K0 = [ eye(nx),               zeros(nx,m+nw);
           Ahat,                  Bhat;
           Cstatic,               Dstatic ];

    M0 = [ zeros(nx),             X,                         zeros(nx,nY);
           X,                     zeros(nx),                 zeros(nx,nY);
           zeros(nY,nx),          zeros(nY,nx),              Qstatic ];

    Phi11 = K0'*M0*K0;
    Fz = [Czbar, Dzbar];

    % Schur complement form for induced L2-gain < gamma:
    %   Phi11 + (1/gamma)*Fz'*Fz < 0.
    MainLMI = [Phi11, Fz';
               Fz,    -gamma*eye(nz)];

    Constraints = [Constraints, MainLMI <= -lmiTol*eye(size(MainLMI,1))];

    if isempty(solverName)
        opts = sdpsettings('verbose',0);
    else
        opts = sdpsettings('solver',solverName,'verbose',0);
    end

    diagnostics = optimize(Constraints,gamma,opts);

    out = struct();
    out.problem = diagnostics.problem;
    out.info = diagnostics.info;
    if diagnostics.problem == 0 || diagnostics.problem == 3 || diagnostics.problem == 4
        out.gamma = value(gamma);
    else
        out.gamma = NaN;
    end
    out.status = yalmiperror(diagnostics.problem);
end

function [A,B,C,D] = basis_realization(nu,rho,basisType)
% Realization of basis functions in Eq. (12):
%   12a: psi = [1; 1/(s-rho); ...; 1/(s-rho)^nu]
%   12b: psi = [1; ((s+rho)/(s-rho)); ...; ((s+rho)/(s-rho))^nu]
% rho should be negative.

    if nu == 0
        A = zeros(0,0); B = zeros(0,1); C = zeros(1,0); D = 1;
        return;
    end

    switch lower(basisType)
        case '12a'
            A = rho*eye(nu) + diag(ones(nu-1,1),-1);
            B = [1; zeros(nu-1,1)];
            C = [zeros(1,nu); eye(nu)];
            D = [1; zeros(nu,1)];

        case '12b'
            s = tf('s');
            psi = tf(zeros(nu+1,1));
            for k = 0:nu
                psi(k+1,1) = ((s + rho)/(s - rho))^k;
            end
            psiSS = minreal(ss(psi),1e-8,false);
            [A,B,C,D] = ssdata(psiSS);

        otherwise
            error('basisType must be ''12a'' or ''12b''.');
    end
end

function [Ak,Bk,Ck,Dk] = kron_i_realization(A,B,C,D,n)
% Realization of kron(psi,I_n), preserving output ordering
% [psi_0*u; psi_1*u; ...; psi_nu*u].

    if isempty(A)
        Ak = zeros(0,0);
        Bk = zeros(0,n);
        Ck = zeros(n*size(C,1),0);
        Dk = kron(D,eye(n));
    else
        Ak = kron(A,eye(n));
        Bk = kron(B,eye(n));
        Ck = kron(C,eye(n));
        Dk = kron(D,eye(n));
    end
end
